id = "charmed-icons"
name = "Charmed Icons"
version = "0.6.1"
schema_version = 1
authors = ["littensy", "jmesrje <james.a.littlefield@proton.me>"]
description = "ğŸ’ Charming icon theme for projects on Zed"
repository = "https://github.com/jmesrje/zed-charmed-icons"
